name: agro_ai_app
description: A voice-based crop disease advisory app
version: 1.0.0+1  # Add this for iOS build metadata

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.4
  path_provider: ^2.0.14
  audioplayers: ^5.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/  # If you're using images or audio files locally
